
[     UTC     ] Logs for v1d0k-mywebsite-streamlit-01home-tq6w3t.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[15:44:12] 🚀 Starting up repository: 'mywebsite', branch: 'main', main module: 'streamlit_01/HOME.py'
[15:44:12] 🐙 Cloning repository...
[15:44:14] 🐙 Cloning into '/app/mywebsite'...

[15:44:14] 🐙 Cloned repository!
[15:44:14] 🐙 Pulling code changes from Github...
[15:44:15] 📦 Processing dependencies...
Check if streamlit is installed

──────────────────────────────── Installing Streamlit ──────────────────────────────────

Collecting streamlit
  Downloading streamlit-1.14.1-py2.py3-none-any.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 52.6 MB/s eta 0:00:00[2022-11-17 15:44:17.321331] 
Collecting rich>=10.11.0
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.5/237.5 KB 141.7 MB/s eta 0:00:00
Collecting watchdog
  Downloading watchdog-2.1.9-py3-none-manylinux2014_x86_64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 KB 165.3 MB/s eta 0:00:00
Collecting typing-extensions>=3.10.0.0
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.3.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 155.4 MB/s eta 0:00:00[2022-11-17 15:44:18.549279] 
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 169.3 MB/s eta 0:00:00
Collecting tornado>=5.0
  Downloading tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 KB 174.2 MB/s eta 0:00:00[2022-11-17 15:44:18.795234] 
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting altair>=3.2.0
  Downloading altair-4.2.0-py3-none-any.whl (812 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 812.8/812.8 KB 155.7 MB/s eta 0:00:00[2022-11-17 15:44:18.917837] 
Collecting numpy
  Downloading numpy-1.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 153.3 MB/s eta 0:00:00[2022-11-17 15:44:19.872168] 
Collecting protobuf<4,>=3.12
  Downloading protobuf-3.20.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 156.7 MB/s eta 0:00:00[2022-11-17 15:44:20.557025] 
Collecting importlib-metadata>=1.4
  Downloading importlib_metadata-5.0.0-py3-none-any.whl (21 kB)
Collecting validators>=0.2
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting blinker>=1.0.0
  Downloading blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 142.2 MB/s eta 0:00:00[2022-11-17 15:44:21.892587] 
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 110.8 MB/s eta 0:00:00[2022-11-17 15:44:22.036855] 
Collecting pyarrow>=4.0
  Downloading pyarrow-10.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 142.4 MB/s eta 0:00:00
Collecting tzlocal>=1.1
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting pandas>=0.21.0
  Downloading pandas-1.5.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 103.9 MB/s eta 0:00:00
Collecting cachetools>=4.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting semver
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting requests>=2.4
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 134.3 MB/s eta 0:00:00
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 166.9 MB/s eta 0:00:00
Collecting packaging>=14.1
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 116.0 MB/s eta 0:00:00[2022-11-17 15:44:23.998365] 
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.29-py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.5/182.5 KB 165.2 MB/s eta 0:00:00[2022-11-17 15:44:24.131151] 
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 147.9 MB/s eta 0:00:00[2022-11-17 15:44:24.276231] 
Collecting toolz
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 KB 117.3 MB/s eta 0:00:00[2022-11-17 15:44:24.358882] 
Collecting jsonschema>=3.0
  Downloading jsonschema-4.17.0-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.8/83.8 KB 125.3 MB/s eta 0:00:00[2022-11-17 15:44:24.496420] 
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 131.0 MB/s eta 0:00:00[2022-11-17 15:44:24.575563] 
Collecting zipp>=0.5
  Downloading zipp-3.10.0-py3-none-any.whl (6.2 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 163.8 MB/s eta 0:00:00[2022-11-17 15:44:24.897790] 
Collecting pytz>=2020.1
  Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 KB 146.5 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 121.7 MB/s eta 0:00:00[2022-11-17 15:44:25.599971] 
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 KB 168.9 MB/s eta 0:00:00[2022-11-17 15:44:25.675487] 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 KB 166.6 MB/s eta 0:00:00[2022-11-17 15:44:25.791320] 
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 142.2 MB/s eta 0:00:00[2022-11-17 15:44:25.891416] 
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 38.3 MB/s eta 0:00:00[2022-11-17 15:44:26.032254] 
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting decorator>=3.4.0
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.19.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 KB 148.9 MB/s eta 0:00:00
Collecting attrs>=17.4.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 KB 124.0 MB/s eta 0:00:00
Collecting tzdata
  Downloading tzdata-2022.6-py2.py3-none-any.whl (338 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.8/338.8 KB 168.7 MB/s eta 0:00:00[2022-11-17 15:44:27.104618] 
Building wheels for collected packages: validators
  Building wheel for validators (setup.py): started
  Building wheel for validators (setup.py): finished with status 'done'
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=f33b824d519775d51779bafd4fc49c56526f21df891e9558c8ffdaee276714ab
  Stored in directory: /tmp/pip-ephem-wheel-cache-osavxcav/wheels/2d/f0/a8/1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators
Installing collected packages: pytz, commonmark, zipp, watchdog, urllib3, tzdata, typing-extensions, tornado, toolz, toml, smmap, six, semver, pyrsistent, pyparsing, pympler, pygments, protobuf, pillow, numpy, MarkupSafe, idna, entrypoints, decorator, click, charset-normalizer, certifi, cachetools, blinker, attrs, validators, rich, requests, pytz-deprecation-shim, python-dateutil, pyarrow, packaging, jsonschema, jinja2, importlib-metadata, gitdb, tzlocal, pydeck, pandas, gitpython, altair, streamlit
Successfully installed MarkupSafe-2.1.1 altair-4.2.0 attrs-22.1.0 blinker-1.5 cachetools-5.2.0 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 commonmark-0.9.1 decorator-5.1.1 entrypoints-0.4 gitdb-4.0.9 gitpython-3.1.29 idna-3.4 importlib-metadata-5.0.0 jinja2-3.1.2 jsonschema-4.17.0 numpy-1.23.4 packaging-21.3 pandas-1.5.1 pillow-9.3.0 protobuf-3.20.3 pyarrow-10.0.0 pydeck-0.8.0 pygments-2.13.0 pympler-1.0.1 pyparsing-3.0.9 pyrsistent-0.19.2 python-dateutil-2.8.2 pytz-2022.6 pytz-deprecation-shim-0.1.0.post0 requests-2.28.1 rich-12.6.0 semver-2.13.0 six-1.16.0 smmap-5.0.0 streamlit-1.14.1 toml-0.10.2 toolz-0.12.0 tornado-6.2 typing-extensions-4.4.0 tzdata-2022.6 tzlocal-4.2 urllib3-1.26.12 validators-0.20.0 watchdog-2.1.9 zipp-3.10.0
WARNING: You are using pip version 22.0.3; however, version 22.3.1 is available.
You should consider upgrading via the '/home/appuser/venv/bin/python -m pip install --upgrade pip' command.

────────────────────────────────────────────────────────────────────────────────────────

[15:44:47] 📦 Processed dependencies!

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.




2022-11-17 15:45:00.812 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/Streamlit-Fran-website.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/Streamlit-Fran-website.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/Streamlit-Fran-website.mp3'
2022-11-17 15:45:40.893 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/Streamlit-Fran-website.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/Streamlit-Fran-website.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/Streamlit-Fran-website.mp3'
[15:47:53] 🐙 Pulling code changes from Github...
[15:47:56] 📦 Processing dependencies...
[15:47:56] 📦 Processed dependencies!
[15:47:59] 🔄 Updated app!
[15:55:07] 🐙 Pulling code changes from Github...
[15:55:08] 📦 Processing dependencies...
[15:55:08] 📦 Processed dependencies!
[15:55:11] 🔄 Updated app!
2022-11-17 15:55:53.099 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/Streamlit-Fran-website.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/Streamlit-Fran-website.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/Streamlit-Fran-website.mp3'
[16:06:54] 🐙 Pulling code changes from Github...
[16:07:09] 📦 Processing dependencies...
[16:07:09] 📦 Processed dependencies!
[16:07:12] 🔄 Updated app!
2022-11-17 16:08:00.333 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/Streamlit-Fran-website.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/Streamlit-Fran-website.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/Streamlit-Fran-website.mp3'
[16:09:17] ❗️ We have encountered an unexpected problem. If this issue persists, please contact support
[16:09:45] 🐙 Pulling code changes from Github...
[16:09:47] 📦 Processing dependencies...
[16:09:47] 📦 Processed dependencies!
[16:09:50] 🔄 Updated app!
2022-11-17 16:10:00.384 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/Streamlit-Fran-website.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/Streamlit-Fran-website.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/Streamlit-Fran-website.mp3'
[16:11:06] 🐙 Pulling code changes from Github...
[16:11:08] 📦 Processing dependencies...
[16:11:08] 📦 Processed dependencies!
2022-11-17 16:11:08.200 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/audio.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/audio.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/audio.mp3'
[16:11:11] 🔄 Updated app!
2022-11-17 16:11:29.627 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/audio.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/audio.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/audio.mp3'
[16:12:11] 🔌 Disconnecting...
[16:12:12] 🖥 Provisioning machine...
[16:12:12] 🎛 Preparing system...
[16:12:12] ⛓ Spinning up manager process...
2022-11-17 16:12:11.827 Uncaught app exception
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/audio.mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/app/mywebsite/streamlit_01/HOME.py", line 9, in <module>
    st.audio('files/audio.mp3')
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 77, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 295, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/media.py", line 211, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from e
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'files/audio.mp3'
[16:12:15] 🔌 Disconnecting...
[16:12:20] 🖥 Provisioning machine...
[16:12:27] 🎛 Preparing system...
[16:12:27] ⛓ Spinning up manager process...